name = "spoken_light"
main = "src/audio-do.js"
compatibility_date = "2024-05-01"
workers_dev = true

routes = [
  { pattern = "spokenlight.dondlingergc.com", custom_domain = true }
]

[assets]
directory = "public"

[[durable_objects.bindings]]
name = "CAPTION_DO"
class_name = "CaptionDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CaptionDurableObject"]

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "spoken_light_lexicon"
database_id = "e96a4638-add4-43a6-8a3e-e1764b1feef5"
